services:
  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432  
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./dockerfiles/dev/django/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/usr/src/app


  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:

      - '5000:80'

      - '25:25'

      - '143:143'
    volumes:

        - smtp4dev-data:/smtp4dev
    environment:

      - ServerOptions__Urls=http://*:80

      - ServerOptions__HostName=smtp4dev



volumes:
  smtp4dev-data: 