# Generated by Django 4.2.20 on 2025-04-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/product.jpeg', upload_to='products/'),
        ),
    ]
